import { Job, ServiceItem, ContentPost, CustomerRequest, WebsiteSettings } from '../types';
import { WHATSAPP_COUNTRY_CODE, WHATSAPP_JOBS_CHANNEL_URL, WHATSAPP_RAW_NUMBER } from './whatsapp';

const STORAGE_KEYS = {
  INITIALIZED: 'lajpal_initialized_v1',
  JOBS: 'lajpal_jobs_data',
  SERVICES: 'lajpal_services_data',
  POSTS: 'lajpal_content_posts_data',
  REQUESTS: 'lajpal_customer_requests_data',
  SETTINGS: 'lajpal_website_settings_data',
  THEME: 'lajpal_theme_mode',
  ADMIN_SESSION: 'lajpal_admin_session',
};

export const DEFAULT_WEBSITE_SETTINGS: WebsiteSettings = {
  brandName: 'LAJPAL',
  serviceName: 'JOBS UPDATES AND ONLINE APPLY SERVICES',
  whatsappNumber: WHATSAPP_COUNTRY_CODE,
  whatsappDisplay: WHATSAPP_RAW_NUMBER,
  whatsappJobsChannelUrl: WHATSAPP_JOBS_CHANNEL_URL,
  shopAddress: 'Near Main Bazaar, College Road, Punjab, Pakistan',
  shopHours: 'Monday – Saturday: 08:30 AM – 10:00 PM | Sunday: 10:00 AM – 06:00 PM',
  email: 'tahirmaqbool2550dk@gmail.com',
  aboutText: 'LAJPAL is your trusted community technology center providing real-time government & private job alerts, expert online application assistance, e-stamp issuance, professional document printing, and citizen registration services across Pakistan.',
  disclaimer: 'LAJPAL is an independent online facilitation and printing service center providing application assistance and verified job news. We do not claim official affiliation with any government department.',
};

export const INITIAL_SERVICES: ServiceItem[] = [
  // 1. Online Apply Services (14 exact approved items)
  {
    id: 'oa-1',
    name: 'Government Jobs Apply',
    category: 'Online Apply',
    description: 'Complete online form submission for Federal, Punjab, and Provincial public sector departments.',
    iconName: 'Building2',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
    turnaroundTime: 'Same Day',
    requirements: ['CNIC', 'Educational Degrees', 'Passport Size Photo', 'Domicile'],
  },
  {
    id: 'oa-2',
    name: 'Private Jobs Apply',
    category: 'Online Apply',
    description: 'Targeted resume submission and online application across top private firms and corporate portals.',
    iconName: 'Briefcase',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
    turnaroundTime: 'Same Day',
    requirements: ['Updated CV', 'CNIC', 'Experience Certificates'],
  },
  {
    id: 'oa-3',
    name: 'University / College Admissions',
    category: 'Online Apply',
    description: 'Undergraduate, Master & Ph.D. online application submission for Pakistani universities.',
    iconName: 'GraduationCap',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
    turnaroundTime: '1-2 Days',
    requirements: ['Matric / Inter Result Card', 'CNIC / B-Form', 'Father CNIC'],
  },
  {
    id: 'oa-4',
    name: 'Scholarships',
    category: 'Online Apply',
    description: 'HEC, Ehsaas, PEEF, and International scholarship portal form filling with required documentation.',
    iconName: 'Award',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'oa-5',
    name: 'Internship Applications',
    category: 'Online Apply',
    description: 'Government youth paid internships, banking internships, and NGO program submissions.',
    iconName: 'FileCheck',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'oa-6',
    name: 'Test / Exam Applications',
    category: 'Online Apply',
    description: 'Entry tests, recruitment exams, and standardized assessment test registrations.',
    iconName: 'PenTool',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'oa-7',
    name: 'NTS Applications',
    category: 'Online Apply',
    description: 'National Testing Service (NTS) candidate profile creation, job apply, and challan printing.',
    iconName: 'FileText',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'oa-8',
    name: 'PPSC Applications',
    category: 'Online Apply',
    description: 'Punjab Public Service Commission job apply, online fee payment verification, and admission letter generation.',
    iconName: 'CheckCircle2',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'oa-9',
    name: 'FPSC Applications',
    category: 'Online Apply',
    description: 'Federal Public Service Commission recruitment and CSS exam online registration assistance.',
    iconName: 'CheckCircle2',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'oa-10',
    name: 'Punjab Government Applications',
    category: 'Online Apply',
    description: 'Portals under Punjab government departments including PITB jobs, Education, Health, and Police.',
    iconName: 'Landmark',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'oa-11',
    name: 'Other Government Portal Applications',
    category: 'Online Apply',
    description: 'WAPDA, NADRA, Rescue 1122, ASF, Railway, and Autonomous agency portals.',
    iconName: 'Globe',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'oa-12',
    name: 'Online Form Filling',
    category: 'Online Apply',
    description: 'Error-free assistance in filling any specialized or complex online web forms and applications.',
    iconName: 'Edit3',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'oa-13',
    name: 'Challan / Form Printing',
    category: 'Online Apply',
    description: 'High-quality laser printouts of National Bank, State Bank, and portal payment fee challans.',
    iconName: 'Printer',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'oa-14',
    name: 'Application Status Checking',
    category: 'Online Apply',
    description: 'Track candidate status, roll number slips, interview letters, and exam merit lists.',
    iconName: 'Search',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },

  // 2. Vehicle Services (ONLY approved 6 items)
  {
    id: 'vs-1',
    name: 'Token Tax',
    category: 'Vehicle',
    description: 'Online verification and e-payment assistance for motor vehicle annual token tax in Punjab.',
    iconName: 'Car',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'vs-2',
    name: 'Learner Licence',
    category: 'Vehicle',
    description: 'Online DLIMS learner driving licence registration and instantaneous printout issuance.',
    iconName: 'CreditCard',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'vs-3',
    name: 'Driving Licence Guidance',
    category: 'Vehicle',
    description: 'Complete guidance on permanent driving licence test scheduling, files, and requirements.',
    iconName: 'HelpCircle',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'vs-4',
    name: 'Licence Renewal Guidance',
    category: 'Vehicle',
    description: 'Guidance and document checklist for expired driving licence renewal across Punjab.',
    iconName: 'RefreshCw',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'vs-5',
    name: 'Duplicate Registration Card',
    category: 'Vehicle',
    description: 'Assistance in lost vehicle registration book / card re-issuance application.',
    iconName: 'Copy',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'vs-6',
    name: 'E-Registration Card',
    category: 'Vehicle',
    description: 'Download and color PVC printing of modern Punjab excise e-registration smart cards.',
    iconName: 'FileBadge',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },

  // 3. Card & Document Services (10 items)
  {
    id: 'cd-1',
    name: 'Duplicate Card',
    category: 'Card & Document',
    description: 'Assistance for replacement and reprinting of lost identification cards.',
    iconName: 'Copy',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cd-2',
    name: 'PVC Card',
    category: 'Card & Document',
    description: 'Heavy-duty waterproof PVC plastic card printing with crisp thermal colors.',
    iconName: 'CreditCard',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cd-3',
    name: 'Student Card',
    category: 'Card & Document',
    description: 'Custom ID card design and batch printing for schools, colleges, and academies.',
    iconName: 'GraduationCap',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cd-4',
    name: 'Employee Card',
    category: 'Card & Document',
    description: 'Professional company staff badges with lanyard and transparent card holders.',
    iconName: 'UserCheck',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cd-5',
    name: 'Visiting Card',
    category: 'Card & Document',
    description: 'Matt finish, gloss UV, and embossed business card printing.',
    iconName: 'Contact',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cd-6',
    name: 'ID Card',
    category: 'Card & Document',
    description: 'Membership cards, visitor passes, and security identity badge design.',
    iconName: 'Shield',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cd-7',
    name: 'Card Printing',
    category: 'Card & Document',
    description: 'Digital offset & thermal printing for any custom card dimensions.',
    iconName: 'Printer',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cd-8',
    name: 'Document Scanning',
    category: 'Card & Document',
    description: 'High-resolution 600 DPI color scanning to PDF and JPG formats.',
    iconName: 'ScanLine',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cd-9',
    name: 'Card Lamination',
    category: 'Card & Document',
    description: 'Heat lamination pouches in thick 150/250 micron for certificates and cards.',
    iconName: 'Layers',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cd-10',
    name: 'Document Printing',
    category: 'Card & Document',
    description: 'Fast single or double-sided printing of official letters, notices, and agreements.',
    iconName: 'FileText',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },

  // 4. Government Document Services (5 items)
  {
    id: 'gd-1',
    name: 'Domicile',
    category: 'Government Document',
    description: 'Complete guidance, online e-domicile appointment, challan generation, and file submission.',
    iconName: 'FileText',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-2',
    name: 'Family Registration Certificate Guidance',
    category: 'Government Document',
    description: 'Step-by-step guidance on NADRA Pak-ID FRC by birth or by marriage.',
    iconName: 'Users',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-3',
    name: 'B-Form Guidance',
    category: 'Government Document',
    description: 'Information regarding child registration certificate (CRC/B-Form) requirements.',
    iconName: 'UserPlus',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-4',
    name: 'CNIC-related Online Services',
    category: 'Government Document',
    description: 'Assistance for online tracking, renewal guidance, and Pak-ID document uploads.',
    iconName: 'CreditCard',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-5',
    name: 'Other Government Online Applications',
    category: 'Government Document',
    description: 'Facilitation for character certificates, arms license verification, and legal affidavits.',
    iconName: 'ShieldCheck',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },

  // 5. E-Stamp Services (8 items)
  {
    id: 'es-1',
    name: 'E-Stamp Guidance',
    category: 'E-Stamp',
    description: 'Expert advice on correct stamp paper values according to Punjab e-Stamping schedule.',
    iconName: 'HelpCircle',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'es-2',
    name: 'Agreement',
    category: 'E-Stamp',
    description: 'Rental agreement, sales deed, partnership deed, and vehicle purchase contracts.',
    iconName: 'FileCheck',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'es-3',
    name: 'Affidavit',
    category: 'E-Stamp',
    description: 'Legal sworn affidavits for educational admissions, lost documents, and declarations.',
    iconName: 'FileSignature',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'es-4',
    name: 'Stamp Paper Guidance',
    category: 'E-Stamp',
    description: 'Calculation of non-judicial and judicial stamp duty requirements.',
    iconName: 'BookOpen',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'es-5',
    name: 'Different E-Stamp Categories',
    category: 'E-Stamp',
    description: 'Support across all 32+ e-stamp classes: lease, power of attorney, partition, surety bond.',
    iconName: 'ListFilter',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'es-6',
    name: 'E-Stamp Application Guidance',
    category: 'E-Stamp',
    description: 'Creating 32-A Challan on Punjab e-Stamping portal with party CNIC and property details.',
    iconName: 'FilePlus',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'es-7',
    name: 'E-Stamp Printing',
    category: 'E-Stamp',
    description: 'Genuine legal size high-density barcode stamp paper printing.',
    iconName: 'Printer',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'es-8',
    name: 'E-Stamp Verification Guidance',
    category: 'E-Stamp',
    description: 'Real-time online verification of issued e-stamp e-Challans through the PITB portal.',
    iconName: 'CheckCircle',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },

  // 6. Computer & Printing Services (21 items)
  {
    id: 'cp-1',
    name: 'Black & White Printing',
    category: 'Computer & Printing',
    description: 'High-speed 1200 DPI laser printing on 75/80 GSM imported paper.',
    iconName: 'Printer',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-2',
    name: 'Color Printing',
    category: 'Computer & Printing',
    description: 'Vibrant color inkjet and digital laser prints on photo and bond paper.',
    iconName: 'Palette',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-3',
    name: 'Photocopy',
    category: 'Computer & Printing',
    description: 'Fast double-sided photocopying with clear contrast and auto-collation.',
    iconName: 'Copy',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-4',
    name: 'Scanning',
    category: 'Computer & Printing',
    description: 'Batch scanning of books, records, and files sent straight to WhatsApp or email.',
    iconName: 'ScanLine',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-5',
    name: 'Document Printing',
    category: 'Computer & Printing',
    description: 'Official reports, project papers, court files, and books printing.',
    iconName: 'FileText',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-6',
    name: 'Photo Printing',
    category: 'Computer & Printing',
    description: 'Glossy 4x6, 5x7, and A4 high-definition family and portrait photos.',
    iconName: 'Image',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-7',
    name: 'Passport Size Photos',
    category: 'Computer & Printing',
    description: 'Urgent passport and blue/white background photographs in 5 minutes.',
    iconName: 'Camera',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-8',
    name: 'CV Printing',
    category: 'Computer & Printing',
    description: 'Crisp CV prints on premium heavy bond paper for job interviews.',
    iconName: 'FileCheck',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-9',
    name: 'Resume Printing',
    category: 'Computer & Printing',
    description: 'Clean modern resume multi-copy printouts with presentation folders.',
    iconName: 'Briefcase',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-10',
    name: 'Lamination',
    category: 'Computer & Printing',
    description: 'Gloss and matte thermal lamination for degree certificates and notices.',
    iconName: 'Layers',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-11',
    name: 'Spiral Binding',
    category: 'Computer & Printing',
    description: 'Ring and spiral wire binding with clear PVC cover sheets for reports.',
    iconName: 'Book',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-12',
    name: 'Typing',
    category: 'Computer & Printing',
    description: 'Fast computer typing services for letters, applications, and documents.',
    iconName: 'Keyboard',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-13',
    name: 'Urdu Typing',
    category: 'Computer & Printing',
    description: 'InPage / Urdu Nastaleeq typing for legal notices, invitations, and poems.',
    iconName: 'Type',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-14',
    name: 'English Typing',
    category: 'Computer & Printing',
    description: 'Accurate English word processing, office correspondence, and transcription.',
    iconName: 'Type',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-15',
    name: 'Online Form Filling',
    category: 'Computer & Printing',
    description: 'Live in-shop online data entry and verification assistance.',
    iconName: 'Edit',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-16',
    name: 'PDF Printing',
    category: 'Computer & Printing',
    description: 'Direct WhatsApp to print service: send PDF and collect in minutes.',
    iconName: 'FileText',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-17',
    name: 'PDF Creation',
    category: 'Computer & Printing',
    description: 'Digitize hard copy documents into organized, bookmarked searchable PDFs.',
    iconName: 'FilePlus',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-18',
    name: 'PDF Merge',
    category: 'Computer & Printing',
    description: 'Combine multiple scanned degrees, experience letters, and CNIC into one single PDF.',
    iconName: 'GitMerge',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-19',
    name: 'PDF Split',
    category: 'Computer & Printing',
    description: 'Separate selected pages or extract sections from large documents.',
    iconName: 'Scissors',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-20',
    name: 'Image to PDF',
    category: 'Computer & Printing',
    description: 'Convert camera mobile pictures into clean, compressed, upload-ready PDF files.',
    iconName: 'FileImage',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-21',
    name: 'PDF to Image',
    category: 'Computer & Printing',
    description: 'Extract high-resolution JPG/PNG images from PDF pages.',
    iconName: 'Image',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cp-22',
    name: 'Document Editing',
    category: 'Computer & Printing',
    description: 'Proofreading, formatting fixes, header/footer insertion, and page realignment.',
    iconName: 'Edit3',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },

  // 7. CV / Resume Services (11 items)
  {
    id: 'cvr-1',
    name: 'Professional CV',
    category: 'CV / Resume',
    description: 'Executive style curriculum vitae designed to pass Applicant Tracking Systems (ATS).',
    iconName: 'Award',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cvr-2',
    name: 'Resume',
    category: 'CV / Resume',
    description: 'Modern concise 1-page resume highlighting skills, metrics, and achievements.',
    iconName: 'Briefcase',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cvr-3',
    name: 'Job Application',
    category: 'CV / Resume',
    description: 'Formal application drafting tailored to specific government or private job advertisements.',
    iconName: 'Mail',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cvr-4',
    name: 'Cover Letter',
    category: 'CV / Resume',
    description: 'Compelling cover letter written to match your targeted job vacancy.',
    iconName: 'FileText',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cvr-5',
    name: 'CV Editing',
    category: 'CV / Resume',
    description: 'Updating existing CV with recent job roles, new degrees, and verified references.',
    iconName: 'Edit2',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cvr-6',
    name: 'CV Formatting',
    category: 'CV / Resume',
    description: 'Design polish, consistent typography, clean alignment, and bullet structuring.',
    iconName: 'Layout',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cvr-7',
    name: 'CV Printing',
    category: 'CV / Resume',
    description: 'Color or monochrome printout on premium textured bond sheets.',
    iconName: 'Printer',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cvr-8',
    name: 'English CV',
    category: 'CV / Resume',
    description: 'Flawless grammatical English CV drafting suitable for corporate and multinational jobs.',
    iconName: 'FileCheck',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cvr-9',
    name: 'Urdu CV',
    category: 'CV / Resume',
    description: 'Beautiful Nastaleeq Urdu CV for teaching, religious institutions, and local clerical roles.',
    iconName: 'FileText',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cvr-10',
    name: 'Simple CV',
    category: 'CV / Resume',
    description: 'Straightforward clean format for fresh candidates and entry-level positions.',
    iconName: 'File',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'cvr-11',
    name: 'Professional CV Templates',
    category: 'CV / Resume',
    description: 'Wide choice of premium international templates (Canva, Word, LaTeX designs).',
    iconName: 'Grid',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },

  // 8. Graphic Designing Services (14 items)
  {
    id: 'gd-d1',
    name: 'Visiting Card',
    category: 'Graphic Designing',
    description: 'Creative brand identity visiting card designs with print-ready vector files.',
    iconName: 'CreditCard',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d2',
    name: 'Logo Design',
    category: 'Graphic Designing',
    description: 'Distinctive, memorable business and shop logo creation with source formats.',
    iconName: 'Sparkles',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d3',
    name: 'Flex Design',
    category: 'Graphic Designing',
    description: 'Large-scale flex board designs for shopfronts, events, and outdoor signages.',
    iconName: 'Layout',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d4',
    name: 'Banner Design',
    category: 'Graphic Designing',
    description: 'Rollup standee and horizontal advertising banner graphics.',
    iconName: 'Flag',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d5',
    name: 'Poster Design',
    category: 'Graphic Designing',
    description: 'Eye-catching promotional posters for seminars, workshops, and business sales.',
    iconName: 'Image',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d6',
    name: 'Flyer Design',
    category: 'Graphic Designing',
    description: 'Single and double-sided distribution pamphlets and leaflet designs.',
    iconName: 'FileText',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d7',
    name: 'Certificate Design',
    category: 'Graphic Designing',
    description: 'Official diploma, completion, and appreciation certificate layout designs.',
    iconName: 'Award',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d8',
    name: 'Invitation Card',
    category: 'Graphic Designing',
    description: 'Custom wedding, opening ceremony, and family function digital cards.',
    iconName: 'HeartHandshake',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d9',
    name: 'Business Card',
    category: 'Graphic Designing',
    description: 'Luxury corporate card designs with QR code vCard integration.',
    iconName: 'Briefcase',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d10',
    name: 'Social Media Post',
    category: 'Graphic Designing',
    description: 'Attractive Instagram & Facebook square promotional posts.',
    iconName: 'Share2',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d11',
    name: 'Facebook Advertisement',
    category: 'Graphic Designing',
    description: 'High conversion ad creatives formatted for Meta feeds and stories.',
    iconName: 'Megaphone',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d12',
    name: 'WhatsApp Advertisement',
    category: 'Graphic Designing',
    description: 'Optimized status graphics and broadcast image flyers for business.',
    iconName: 'MessageSquare',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d13',
    name: 'YouTube Thumbnail',
    category: 'Graphic Designing',
    description: 'High click-through rate (CTR) thumbnails with clear punchy typography.',
    iconName: 'Video',
    isPopular: false,
    enabled: true,
    showWhatsAppButton: true,
  },
  {
    id: 'gd-d14',
    name: 'Passport Photo Editing',
    category: 'Graphic Designing',
    description: 'Background color replacement (white/blue), formal coat/tie dress editing.',
    iconName: 'UserCheck',
    isPopular: true,
    enabled: true,
    showWhatsAppButton: true,
  },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-1',
    title: 'Punjab Police Constables & Lady Constables (BPS-07) 2026',
    department: 'Punjab Police Department',
    category: 'Police Jobs',
    jobType: 'Permanent',
    advertisementNumber: 'PPD-RECRUIT-2026/09',
    vacancies: 4850,
    bps: 'BPS-07',
    qualification: 'Matriculation (Secondary School Certificate) with minimum 50% marks',
    experience: 'Fresh candidates eligible',
    ageLimit: '18 to 22 Years (Relaxable as per rules)',
    gender: 'Both',
    domicile: 'Punjab Districts',
    province: 'Punjab',
    district: 'All Punjab Districts',
    location: 'Across Punjab Police Lines',
    salary: 'PKR 35,000 - 45,000 / month',
    applicationFee: 'Rs. 200 (Challan Fee)',
    lastDate: '2026-10-18', // Open, days remaining calculated dynamically
    requiredDocuments: [
      'Original CNIC / Smart Card',
      'Matric Certificate & Detailed Marks Sheet',
      'Domicile Certificate of Relevant District',
      'Character Certificate from Head of Institution',
      '8 Passport Size Photos with blue background',
    ],
    applicationMethod: 'Fill online registration form on Punjab Police official portal or submit through LAJPAL online assistance, then submit printed form at District Police Lines.',
    description: 'Applications are invited from suitable candidates having Punjab domicile for recruitment as Constable & Lady Constable in Punjab Police. Candidates must meet the physical measurements (Height: Male 5ft 7in, Female 5ft 2in; Chest for male: 33x34.5 inches).',
    instructions: 'Running test: 1.6 KM in 7 minutes for males; 1.6 KM in 10 minutes for females. Only candidates qualifying physical tests will appear in written examination.',
    officialSource: 'punjabpolice.gov.pk',
    officialApplyLink: 'https://punjabpolice.gov.pk',
    showOfficialApply: true,
    showWhatsAppApply: true,
    featured: true,
    published: true,
    advertisementImages: [
      'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=1200&q=80',
    ],
    createdAt: '2026-09-20',
    updatedAt: '2026-09-20',
  },
  {
    id: 'job-2',
    title: 'Educators & AEOs Recruitment 2026 (Elementary & Secondary)',
    department: 'School Education Department, Punjab',
    category: 'Education Jobs',
    jobType: 'Contract',
    advertisementNumber: 'SED-PUNJAB-2026/04',
    vacancies: 11200,
    bps: 'BPS-14 to BPS-16',
    qualification: 'BS / Master Degree (16 Years) in relevant subjects with B.Ed / M.Ed',
    experience: 'Not compulsory, fresh graduates encouraged',
    ageLimit: '20 to 30 Years (+ 5 Years General Relaxation for Male, + 8 Years for Female)',
    gender: 'Both',
    domicile: 'Respective Tehsil / District of Punjab',
    province: 'Punjab',
    district: 'All Punjab Districts',
    location: 'District Public Schools',
    salary: 'PKR 45,000 - 70,000 / month',
    applicationFee: 'Rs. 600 (PPSC/NTS Challan)',
    lastDate: '2026-10-25', // Open
    requiredDocuments: [
      'Online Application Form copy',
      'All Academic transcripts (Matric to Master)',
      'Domicile Certificate',
      'B.Ed Degree/Transcript if available',
      'CNIC copy & 4 Photographs',
    ],
    applicationMethod: 'Online apply via recruitment portal. LAJPAL provides complete error-free document verification and online form filing.',
    description: 'Government of the Punjab, School Education Department announces mega recruitment of Educators (ESE, SESE, SSE) and Assistant Education Officers (AEOs) in all 36 districts of Punjab.',
    instructions: 'Selection criteria is purely merit-based determined by academic marks weightage and NTS/PPSC screening test score.',
    officialSource: 'schools.punjab.gov.pk',
    officialApplyLink: 'https://schools.punjab.gov.pk',
    showOfficialApply: true,
    showWhatsAppApply: true,
    featured: true,
    published: true,
    advertisementImages: [
      'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
    ],
    createdAt: '2026-09-22',
    updatedAt: '2026-09-22',
  },
  {
    id: 'job-3',
    title: 'Assistant Directors & Inspectors (BPS-17 / BPS-16) via FPSC',
    department: 'Federal Investigation Agency (FIA) / FPSC',
    category: 'Federal Jobs',
    jobType: 'Permanent',
    advertisementNumber: 'FPSC Consolidated Adv 10/2026',
    vacancies: 340,
    bps: 'BPS-16 & BPS-17',
    qualification: 'Second Class or Grade C Master Degree or 16 Years Equivalent from HEC recognized university',
    experience: 'Fresh graduates eligible',
    ageLimit: '22 to 28 Years (+ 5 Years Federal General Relaxation)',
    gender: 'Both',
    domicile: 'Merit, Punjab, Sindh, KPK, Balochistan, AJK, GB',
    province: 'Federal / All Pakistan',
    district: 'Nationwide',
    location: 'Islamabad, Lahore, Karachi, Peshawar, Quetta',
    salary: 'PKR 65,000 - 95,000 / month',
    applicationFee: 'Rs. 300 for BS-16 / Rs. 500 for BS-17 (NBP Challan)',
    lastDate: '2026-10-15', // Open
    requiredDocuments: [
      'FPSC Treasury Challan receipt',
      'CNIC',
      'Degree Transcript with CGPA/Percentage',
      'Domicile Certificate',
    ],
    applicationMethod: 'Submit online form on FPSC website. No hard copies required at application stage.',
    description: 'Federal Public Service Commission announces general recruitment for Assistant Directors (Investigation) BS-17 and Inspectors BS-16 in FIA.',
    instructions: 'Download admission certificates from FPSC website one week before test date. Testing centers available in all major divisional headquarters.',
    officialSource: 'fpsc.gov.pk',
    officialApplyLink: 'https://www.fpsc.gov.pk',
    showOfficialApply: true,
    showWhatsAppApply: true,
    featured: true,
    published: true,
    createdAt: '2026-09-18',
    updatedAt: '2026-09-18',
  },
  {
    id: 'job-4',
    title: 'Pakistan Army Commissioned Officers (PMA 158 Long Course)',
    department: 'Pakistan Army (Join Pak Army)',
    category: 'Army Jobs',
    jobType: 'Permanent',
    advertisementNumber: 'PMA-158-LC/2026',
    vacancies: 600,
    bps: 'Commissioned Officer (Second Lieutenant)',
    qualification: 'Intermediate (FA/F.Sc) with minimum 55% marks or Graduates with 60% marks',
    experience: 'Not applicable',
    ageLimit: '17 to 22 Years (Unmarried Male Citizens)',
    gender: 'Male',
    domicile: 'All Pakistan & AJK / Gilgit Baltistan',
    province: 'All Pakistan',
    district: 'All Districts',
    location: 'PMA Kakul, Abbottabad',
    salary: 'As per Army Officer Pay Scale with extensive allowances and housing',
    applicationFee: 'Rs. 100 (Prospectus/Registration fee)',
    lastDate: '2026-10-30', // Open
    requiredDocuments: [
      'Original Matric & Inter Certificates with 2 sets of attested copies',
      'Original CNIC or NADRA Smart Card with Father CNIC',
      '3 Passport size photos attested',
    ],
    applicationMethod: 'Register online at Join Pak Army portal or visit nearest Army Selection & Recruitment Centre (AS&RC).',
    description: 'Pakistan Army invites patriotic Pakistani young men to join as Regular Commissioned Officers through PMA 158 Long Course at Pakistan Military Academy Kakul.',
    instructions: 'Preliminary written test, intelligence test, initial medical test and physical test (1.6 KM run, pull-ups, push-ups, ditch crossing).',
    officialSource: 'joinpakarmy.gov.pk',
    officialApplyLink: 'https://joinpakarmy.gov.pk',
    showOfficialApply: true,
    showWhatsAppApply: true,
    featured: true,
    published: true,
    createdAt: '2026-09-24',
    updatedAt: '2026-09-24',
  },
  {
    id: 'job-5',
    title: 'National Bank of Pakistan (NBP) Trainee Officers Program 2026',
    department: 'National Bank of Pakistan',
    category: 'Bank Jobs',
    jobType: 'Permanent',
    advertisementNumber: 'NBP-HR-2026/08',
    vacancies: 250,
    bps: 'OG-II / OG-III',
    qualification: 'Graduation / Master Degree (16 Years) in Business, Commerce, Economics, Banking, CS or IT with 60% marks or 2.5 CGPA',
    experience: 'Fresh graduates only',
    ageLimit: 'Max 26 Years as of closing date',
    gender: 'Both',
    domicile: 'All Pakistan Provincial Quotas',
    province: 'All Pakistan',
    location: 'Branches across Pakistan',
    salary: 'PKR 60,000 - 80,000 / month with bank allowances',
    applicationFee: 'Rs. 500 (Testing agency fee)',
    lastDate: '2026-10-10', // Open
    requiredDocuments: [
      'Updated Professional Resume',
      'Degree / Transcript Copy',
      'CNIC Copy',
      'Recent Passport Photograph',
    ],
    applicationMethod: 'Apply online through authorized testing portal or contact LAJPAL for application assistance and profile preparation.',
    description: 'NBP invites applications from dynamic, energetic, and self-motivated graduates for Trainee Officer / Management Trainee positions across Pakistan.',
    instructions: 'Comprehensive written test followed by panel interviews. Selected candidates will undergo intensive banking training before permanent placement.',
    officialSource: 'nbp.com.pk',
    officialApplyLink: 'https://www.nbp.com.pk',
    showOfficialApply: true,
    showWhatsAppApply: true,
    featured: false,
    published: true,
    createdAt: '2026-09-15',
    updatedAt: '2026-09-15',
  },
  {
    id: 'job-6',
    title: 'University Teaching Assistants & Research Fellows 2026',
    department: 'Punjab University Lahore',
    category: 'University Jobs',
    jobType: 'Contract',
    advertisementNumber: 'PU-REC-2026/12',
    vacancies: 80,
    bps: 'BPS-17 Equivalent',
    qualification: 'MS / M.Phil (18 Years) in relevant disciplines with no 3rd division in academic career',
    experience: 'Research publication preferred',
    ageLimit: '22 to 35 Years',
    gender: 'Both',
    domicile: 'Punjab',
    province: 'Punjab',
    district: 'Lahore',
    location: 'New Campus, Lahore',
    salary: 'PKR 55,000 - 75,000 / month stipend',
    applicationFee: 'Rs. 1000 (PU Bank Challan)',
    lastDate: '2026-10-05', // Open - 7 days left from 28 Sep
    requiredDocuments: [
      'Published research papers list',
      'MS/M.Phil degree transcript attested by HEC',
      'CNIC and Domicile',
      '2 Reference Letters',
    ],
    applicationMethod: 'Submit online form on PU Career portal and deposit fee at HBL PU branch.',
    description: 'Punjab University requires Research Associates and Teaching Fellows across faculties of Sciences, Computing, and Management.',
    instructions: 'Shortlisted applicants will be called for interview before departmental selection board.',
    officialSource: 'pu.edu.pk',
    officialApplyLink: 'https://pu.edu.pk',
    showOfficialApply: true,
    showWhatsAppApply: true,
    featured: false,
    published: true,
    createdAt: '2026-09-10',
    updatedAt: '2026-09-10',
  },
  {
    id: 'job-7',
    title: 'Prime Minister Youth National Internship Program (Batch 2026)',
    department: 'Ministry of Federal Education & Professional Training',
    category: 'Internship',
    jobType: 'Internship',
    advertisementNumber: 'PM-YIP-2026',
    vacancies: 15000,
    qualification: 'Graduates with 16 years education in any field',
    experience: 'No experience needed',
    ageLimit: 'Up to 30 Years',
    gender: 'Both',
    domicile: 'Nationwide all provinces',
    province: 'All Pakistan',
    location: 'Public & Private Organizations in applicant home district',
    salary: 'PKR 25,000 / month paid stipend for 6 months',
    applicationFee: 'Nil (Free application)',
    lastDate: '2026-10-20',
    requiredDocuments: [
      'Graduation Degree / Transcript',
      'CNIC copy',
      'Domicile certificate',
    ],
    applicationMethod: 'Apply online on Prime Minister Youth Program official portal.',
    description: 'Federal government paid youth internship scheme placing recent university graduates in government offices, schools, and partner corporate institutions.',
    instructions: 'Selection will be automated based on district quotas, gender parity, and verified graduation merit.',
    officialSource: 'pmyp.gov.pk',
    officialApplyLink: 'https://pmyp.gov.pk',
    showOfficialApply: true,
    showWhatsAppApply: true,
    featured: true,
    published: true,
    createdAt: '2026-09-21',
    updatedAt: '2026-09-21',
  },
  {
    id: 'job-8',
    title: 'Punjab Revenue Authority (PRA) Inspectors & IT Assistants (Closed)',
    department: 'Punjab Revenue Authority',
    category: 'Government Jobs',
    jobType: 'Permanent',
    advertisementNumber: 'PRA-RECRUIT-2026/02',
    vacancies: 120,
    bps: 'BPS-16',
    qualification: 'Bachelor Degree in Commerce / Economics / Computer Science',
    experience: '1 year relevant experience',
    ageLimit: '21 to 30 Years',
    gender: 'Both',
    domicile: 'Punjab',
    province: 'Punjab',
    location: 'Lahore, Rawalpindi, Faisalabad, Multan',
    salary: 'PKR 55,000 - 80,000 / month',
    lastDate: '2026-09-15', // Past date -> Automatically Closed!
    requiredDocuments: ['CNIC', 'Academic Certificates', 'Domicile'],
    description: 'Recruitment for Enforcement Officers and IT assistants in provincial sales tax jurisdiction.',
    officialSource: 'pra.punjab.gov.pk',
    showOfficialApply: false,
    showWhatsAppApply: true,
    featured: false,
    published: true,
    createdAt: '2026-08-15',
    updatedAt: '2026-09-16',
  },
  {
    id: 'job-9',
    title: 'Rescue 1122 Emergency Medical Technicians (EMT) - (Past Deadline)',
    department: 'Punjab Emergency Service Department (Rescue 1122)',
    category: 'Government Jobs',
    jobType: 'Permanent',
    advertisementNumber: 'PES-1122-2026/07',
    vacancies: 650,
    bps: 'BPS-12',
    qualification: 'Nursing / Paramedical Diploma / BS Allied Health',
    ageLimit: '20 to 30 Years',
    gender: 'Both',
    domicile: 'Punjab',
    province: 'Punjab',
    location: 'All Punjab Tehsils',
    lastDate: '2026-09-20', // Past date -> Automatically Closed!
    requiredDocuments: ['CNIC', 'Paramedic Diploma', 'Physical fitness report'],
    description: 'Recruitment for front-line emergency ambulance medical technicians.',
    officialSource: 'rescue.gov.pk',
    showOfficialApply: false,
    showWhatsAppApply: true,
    featured: false,
    published: true,
    createdAt: '2026-08-20',
    updatedAt: '2026-09-21',
  },
];

export const INITIAL_POSTS: ContentPost[] = [
  {
    id: 'post-1',
    title: 'PPSC Consolidated Advertisement No. 12/2026 Announced with 1400+ Vacancies',
    postType: 'Advertisements',
    date: '2026-09-25',
    description: 'Punjab Public Service Commission has officially released Consolidated Advertisement No. 12/2026 featuring Sub-Inspectors, Tehsildars, Lecturers, and Accounts Officers. Visit LAJPAL for online form submission and fee challan preparation.',
    featuredImage: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1000&q=80',
    officialWebsiteLink: 'https://www.ppsc.gop.pk',
    showWhatsAppButton: true,
    featured: true,
    published: true,
    expiryDate: '2026-10-31',
    createdAt: '2026-09-25',
    updatedAt: '2026-09-25',
  },
  {
    id: 'post-2',
    title: 'HEC Need-Based & Ehsaas Undergraduate Scholarships Fall 2026 Online Portal Open',
    postType: 'Scholarships',
    date: '2026-09-24',
    description: 'Higher Education Commission Pakistan has opened registration for Need-Based Scholarships covering 100% university tuition fee along with PKR 6,000 monthly living allowance for deserving undergraduate students.',
    featuredImage: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1000&q=80',
    officialWebsiteLink: 'https://www.hec.gov.pk',
    showWhatsAppButton: true,
    featured: true,
    published: true,
    expiryDate: '2026-11-15',
    createdAt: '2026-09-24',
    updatedAt: '2026-09-24',
  },
  {
    id: 'post-3',
    title: 'Punjab Motor Vehicle Token Tax E-Payment Concession Last Date Reminder',
    postType: 'Important Dates',
    date: '2026-09-23',
    description: 'Excise & Taxation Department Punjab reminds vehicle owners to pay annual token tax via e-Pay Punjab before the end of the quarter to enjoy rebate and avoid 100% late surcharges. Pay easily at LAJPAL Computer Shop.',
    featuredImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80',
    showWhatsAppButton: true,
    featured: false,
    published: true,
    expiryDate: '2026-10-05',
    createdAt: '2026-09-23',
    updatedAt: '2026-09-23',
  },
  {
    id: 'post-4',
    title: 'Government College University (GCU) & UET Fall Admissions 2026 Schedule',
    postType: 'Admissions',
    date: '2026-09-20',
    description: 'Admissions open for BS Engineering, Computer Science, and Social Sciences. Candidates can process their online registration, voucher generation, and entry test confirmation at our service counter.',
    featuredImage: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1000&q=80',
    officialWebsiteLink: 'https://uet.edu.pk',
    showWhatsAppButton: true,
    featured: false,
    published: true,
    expiryDate: '2026-10-12',
    createdAt: '2026-09-20',
    updatedAt: '2026-09-20',
  },
];

export const INITIAL_REQUESTS: CustomerRequest[] = [
  {
    id: 'REQ-20260928-001',
    customerName: 'Muhammad Rizwan',
    mobileNumber: '0301-7654321',
    whatsappNumber: '0301-7654321',
    serviceName: 'Government Jobs Apply',
    message: 'Need help applying for Punjab Police Constable 2026 advertisement. I have uploaded my matric certificate and domicile.',
    requiredDocuments: ['Matric Certificate', 'CNIC', 'Domicile'],
    preferredContactMethod: 'WhatsApp',
    status: 'Processing',
    adminNotes: 'Challan generated and sent to customer via WhatsApp. Awaiting fee confirmation.',
    createdAt: '2026-09-28 10:15 AM',
    updatedAt: '2026-09-28 11:30 AM',
  },
  {
    id: 'REQ-20260927-002',
    customerName: 'Ayesha Bibi',
    mobileNumber: '0312-9876543',
    whatsappNumber: '0312-9876543',
    serviceName: 'Professional CV',
    message: 'I need an ATS-friendly CV for teacher job vacancy in Education Department.',
    preferredContactMethod: 'WhatsApp',
    status: 'Completed',
    adminNotes: 'Draft approved by candidate. Final PDF sent on WhatsApp and 3 hard copies printed.',
    createdAt: '2026-09-27 02:40 PM',
    updatedAt: '2026-09-27 05:10 PM',
  },
];

// Helper functions for safe storage access
export function getStoredData<T>(key: string, defaultValue: T): T {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return defaultValue;
    return JSON.parse(raw) as T;
  } catch (e) {
    console.warn(`Error reading localStorage for key ${key}:`, e);
    return defaultValue;
  }
}

export function setStoredData<T>(key: string, value: T): boolean {
  try {
    localStorage.setItem(key, JSON.stringify(value));
    return true;
  } catch (e) {
    console.error(`Error saving localStorage for key ${key}:`, e);
    return false;
  }
}

/**
 * Initializes default demo data if and ONLY if it has never been initialized before.
 * Never overwrites user updates on page reload.
 */
export function initializeStorageIfNeeded(): void {
  const isInitialized = localStorage.getItem(STORAGE_KEYS.INITIALIZED);
  if (!isInitialized) {
    localStorage.setItem(STORAGE_KEYS.JOBS, JSON.stringify(INITIAL_JOBS));
    localStorage.setItem(STORAGE_KEYS.SERVICES, JSON.stringify(INITIAL_SERVICES));
    localStorage.setItem(STORAGE_KEYS.POSTS, JSON.stringify(INITIAL_POSTS));
    localStorage.setItem(STORAGE_KEYS.REQUESTS, JSON.stringify(INITIAL_REQUESTS));
    localStorage.setItem(STORAGE_KEYS.SETTINGS, JSON.stringify(DEFAULT_WEBSITE_SETTINGS));
    localStorage.setItem(STORAGE_KEYS.INITIALIZED, 'true');
  }
}

export { STORAGE_KEYS };
